spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sberChat
    username: postgres
    password: 111
    driver-class-name: org.postgresql.Driver
    data: classpath:data.sql
    initialize: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect